CREATE TABLE pisa_data AS
SELECT *
FROM edstats_data
WHERE indicator_code IN ('LO.PISA.MAT', 'LO.PISA.MAT.FE', 'LO.PISA.MAT.MA',
'LO.PISA.MAT.0', 'LO.PISA.MAT.1', 'LO.PISA.MAT.2', 'LO.PISA.MAT.3', 'LO.PISA.MAT.4', 'LO.PISA.MAT.5', 'LO.PISA.MAT.6',
'LO.PISA.MAT.P05', 'LO.PISA.MAT.P10', 'LO.PISA.MAT.P25', 'LO.PISA.MAT.P50', 'LO.PISA.MAT.P75', 'LO.PISA.MAT.P90', 'LO.PISA.MAT.P95',
'LO.PISA.REA', 'LO.PISA.REA.FE', 'LO.PISA.REA.MA',
'LO.PISA.REA.0', 'LO.PISA.REA.1A', 'LO.PISA.REA.1B', 'LO.PISA.REA.2', 'LO.PISA.REA.3', 'LO.PISA.REA.4', 'LO.PISA.REA.5', 'LO.PISA.REA.6',
'LO.PISA.REA.P05', 'LO.PISA.REA.P10', 'LO.PISA.REA.P25', 'LO.PISA.REA.P50', 'LO.PISA.REA.P75', 'LO.PISA.REA.P90', 'LO.PISA.REA.P95',
'LO.PISA.SCI', 'LO.PISA.SCI.FE', 'LO.PISA.SCI.MA',
'LO.PISA.SCI.0', 'LO.PISA.SCI.1A', 'LO.PISA.SCI.1B', 'LO.PISA.SCI.2', 'LO.PISA.SCI.3', 'LO.PISA.SCI.4', 'LO.PISA.SCI.5', 'LO.PISA.SCI.6',
'LO.PISA.SCI.P05', 'LO.PISA.SCI.P10', 'LO.PISA.SCI.P25', 'LO.PISA.SCI.P50', 'LO.PISA.SCI.P75', 'LO.PISA.SCI.P90', 'LO.PISA.SCI.P95');
